* Com2.e computer science project
** Overview
   - The project allows you to increase your final grade by a maximum
     of 3 grades (maximum level 3 in grading levels below)
   - Your program must process text data in a meaningful way, but you
     should not strive for a real-world application.
   - Grading is based on
     - specification
     - correctness
     - code clarity.
   - An example is provided for you below.

** Project deadline
   The dealine of the project is <2022-11-20 Sun 23:59>.

** Project submission
   - Your submission consists of
     1. one *PDF file* containing documentation
        1. your target grade level (1, 2 or 3)
        2. specification
        3. test case with typical input
     2. one ~.java~-file containing the code
     3. possibly one or more text data files needed for the test case.
   - Submission is made via email by providing either
     - one ~.zip~-archive containing all files, or
     - a link to a GitHub repository containing all files.
   - It is strongly suggested that you use documentation structure
     similar to the example below, as this will make both your and my
     life a lot easier.
   
** Grading levels
*** Criteria for level 1
**** Specification
     - There is a sensible description of what the program does.
     - The program reads input from the user and/or from a text data
       file and performs a meaningful operation.
     - Format of input is explained clearly.
     - The input contains multiple items of data (multiple numbers, or
       multiple lines of text, or similar).
     - At least some of the data is read from the user or from a file
       using a loop (~while~, ~for~).
       - Note: There are /many/ ways to do this. Read multiple lines
         from a file. Repeat the same operation multiple times for the
         user. Read multiple lines from user input.
**** Correctness and exception handling
     - The program works correctly in one documented test case with
       typical input.
     - If any text data files are required to test this, they are
       supplied.
**** Code clarity
     - Code is indented correctly.
     - There is no unnecessary whitespace (no extra empty lines or
       extra spaces).
     - Identifiers (names of variables, constants and functions) are
       meaningful in the context of the program.
*** Additional criteria for level 2
**** Use of data structures
     - Program uses arrays and/or lists in a meaningful way. That is,
       it would not be possible to program the functionality without a
       data structure.
**** Algorithms
     - Program includes at least one non-trivial algorithm. This could
       be searching or sorting or something else.
**** Code clarity
     - Constants are identified and named.
     - All non-trivial parts of the code are
       commented. \ldquo{}Non-trivial\rdquo is defined by assuming
       that the reader is a fellow student.
*** Additional criteria for level 3
**** Data structures
     - Program includes at least one programmer-defined class.
**** Code clarity
     - The flow of the program is split into meaningful functions
       called by ~main()~.
     - The role of defined functions is explained in comments.
** Example project
*** Documentation
**** Target assessment level
     Target assessment level of this work is 3.
**** Specification
***** What does the program do?
      The program
      1. reads data about animals from a file
      2. allows user to search for an animal based on its species
***** Data format
       The input data text file consists of lines, each line
       containing
       #+begin_center
       =category weight species=
       #+end_center
       =category= is a single word, =weight= is a nonnegative integer,
       and =species= is the rest of the line.
**** Correctness and exception handling
***** Typical test case
      File [[file:animals.txt]] contains data from 4 animals. The
      following is a script obtained when running the program

      #+RESULTS: run-application
      : Cash Michael Las Vegas, US
      : Knight Michael Moving truck
      : Burnham Michael The final frontier
      : McGyver Agnus Phoenix, Foundation
      : Doe Jane Aberdeen, Scotland
      : Tarzan Jane Greystoke, UK

***** Exception handling (levels 2 and 3)
      The following are all the possible exceptions / special cases
      and the way they are handled.
      - More than one program argument: only the first one is used as
        name of data file.
      - Reading user-supplied data file name fails: exception is
        caught and printed to user, program exits.
      - Opening data file for reading fails: exception is caught and
        printed to user, program exits.
      - Reading data from data file fails: exception caught and
        printed, program exits.
      - Number of persons exceeds program constant: reported to user,
        program exits.

***** Resource management (level 3)
      The following resources are opened with ~try~-with-resources
      -statements and are therefore closed automatically when the
      program no longer needs them, even in the case of an exception.
      - ~Scanner~ for system input when reading user-supplied file
        name.
      - ~Scanner~ when reading data file.

*** Program code (provided here just for ease of reading, would be a separate file in your submission)
    #+begin_src java :exports code :tangle Main.java
      import java.io.File;
      import java.util.Scanner;
      import java.util.LinkedList;

      public class Main
      {
        public static void main (String[] args) throws Exception
        {
          final String filename = "animals.txt";

          // read animals from file
          Animal[] animals = readAnimals (filename);

          // sort into increasing lexicographic order according to species
          sortAnimals (animals);

          // search for animal whose species starts with given key; quit
          // with input !
          Scanner scanner = new Scanner (System.in);
          boolean quit = false;
          while (!quit)
          {
            System.out.print ("Please give search key (! to quit): ");
            String key = scanner.next ();
            if (key.equals ("!"))
              quit = true;
            else
            {
              LinkedList<Animal> animalList = searchAnimal (animals, key);
              if (!animalList.empty ())
                for (int i = 0; i < animalList.size (); i++)
                  System.out.println (animalList.get (i));
              else
                System.out.println ("<key not found>");
            }
          }
        }

        // read animals from given file name, return array of animals
        static Animal[] readAnimals (String filename) throws Exception
        {
          // open file and create a scanner for it
          Scanner scanner = new Scanner (new File (filename));

          // first store animals into list, since we do not know how many
          // there are
          LinkedList<Animal> animalList = new LinkedList<> ();

          // read while there are lines in the file
          while (scanner.hasNextLine ())
          {
            // each line has category, weight, species
            String category = scanner.next ();
            int weight = scanner.nextInt ();

            // species is the rest of the line, with possible leading and
            // trailing whitespace trimmed
            String species = scanner.nextLine ().trim (); 

            animalList.add (new Animal (species, category, weight));
          }

          // store animals into returned array
          int numAnimals = animalList.size ();
          Animal[] animals = new Animal [numAnimals];
          for (int i = 0; i < numAnimals; i++)
            animals [i] = animalList.get (i);

          return animals;
        }

        // sort animals according to species into increasing lexicographic
        // order
        static void sortAnimals (Animal[] animals)
        {
          // selection sort according to species name
          for (int i = 0; i < animals.length - 1; i++)
            for (int j = i + 1; j < animals.length; j++)
              if (animals [i].species.compareTo (animals [j].species) > 0)
              {
                Animal tmp = animals [i];
                animals [i] = animals [j];
                animals [j] = tmp;
              }
        }

        // do a binary search for an animal whose species starts with key
        static LinkedList<Animal> searchAnimal (Animal[] animals, String key)
        {
          int lo = 0, hi = animals.length - 1;
          int foundInd = -1;

          while (lo <= hi)
          {
            int mid = (lo + hi) / 2;
            Animal a = animals [mid];
            if (a.species.startsWith (key))
            {
              foundInd = mid;;
              break;
            }
            else if (a.species.compareTo (key) > 0)
              hi = mid - 1;
            else
              lo = mid + 1;
          }

          LinkedList<Animal> animalList = new LinkedList<> ();

          if (foundInd >= 0)
            while (foundInd > 0 && animals [foundInd - 1].species.startsWith (key))
              foundInd--;

          while (foundInd < animals.length && animals [foundInd].startsWith (key))
          {
            animalList.add (animals [foundInd]);
            foundInd++;
          }

          return animalList;
        }
      }


      class Animal
      {
        public Animal (String species, String category, int weight)
        {
          this.species = species;
          this.category = category;
          this.weight = weight;
        }

        public String toString ()
        {
          return species + " (" + category + ") " + weight;
        }

        public String species, category;
        public int weight;
      }
    #+end_src
